[project]
name = "climate-risk-project-swi-ms-a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "geopandas>=1.1.1",
    "pandas>=2.3.3",
    "scikit-gstat>=1.0.21",
    "scipy>=1.15.3",
    "seaborn>=0.13.2",
]
